project:
  type: website

website:
  page-navigation: true
  page-footer: 
    center: "<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/'><img src='https://mirrors.creativecommons.org/presskit/logos/cc.logo.large.png' style='width:100px'></a>"
  title: "Ciência de dados"
  navbar:
    left:
      - text: Curso
        menu:
          - text: Estatística
            href: curso/estatistica/curso_estatistica.qmd
          - text: R
            href: curso/r/curso_r.qmd
      - blog.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/flavianowilliams/education
  
format:
  html:
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
    theme:
      - sketchy
      - brand
    css: styles.css
    toc: true
bibliography: bibliografia.bib
csl: abnt.csl
lang: "pt-BR"
date-format: DD/MM/YYYY

execute:
  freeze: false